name: baddie_app
description: Baddie - Your Savage AI Friend
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  speech_to_text: ^6.6.0
  http: ^1.1.0
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.0

flutter:
  uses-material-design: true
